apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::129271359144:user/TerraformUser
     username: terraform-user
     groups:
       - system:masters

mapRoles: |
  - rolearn: arn:aws:iam::129271359144:role/GitHubActionsRole
   username: github-actions
   groups:
     - system:masters
