apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::129271359144:user/TerraformUser
      username: TerraformUser
      groups:
        - system:masters
